set tool "clc"
set exp_internal 1
set vect "\[ .4 .5 .6 \]"
set dims "\[ 5 5 \]"
set testdata {
    {"\"3 + 4\"" "7" }
    {"\"3 - 4\"" "-1" }
    {"\"3 * 4\"" "12" }
    {"\"3 / 4\"" "0.75" }
    {"\"1+2+3\"" "6" }
    {"\"1-2-3\"" "2" }
    {"\"(1-2)-3\"" "-4" }
    {"\"1-(2-3)\"" "2" }
    
    {"\"3 + $vect \"" "3.4 3.5 3.6" }
    {"\"$vect ^ 3 \"" "0.064 0.125 0.216" }

    {"\"(5*5)<>($dims <> $vect)/8\"" "0.05 0.0625 0.075 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0" }
    {"\",$dims <> $vect\"" "0.4 0.5 0.6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0" }
    
    {"\"sin(45d) \"" "0.707107" }
    {"\"cos(45d) \"" "0.707107" }
    {"\"tan(45d) \"" "1" }
    {"\"tan($vect) \"" "0.422793 0.546302 0.684137" }
    {"\"atan(tan($vect)) \"" "0.4 0.5 0.6" }
    {"\"asin(sin(1)) \"" "1" }
    {"\"acos(cos(1)) \"" "1" }
}

global CLC
foreach pattern $testdata {
    set inputs [lindex $pattern 0]
    eval "spawn $CLC -e $inputs"
    expect {
        -re [lindex $pattern 1] {
            pass $inputs
        }
        default { fail $inputs}
    }
}

